version: 2

builds:
  - main: ./cmd/todoui
    binary: todoui
    ldflags:
      - -s -w
      - -X github.com/datapointchris/todoui/internal/cli.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "todoui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
